name: immatch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - python=3.7
  - pytorch==1.7.0
  - torchvision
  - jupyter
  - scipy
  - matplotlib
  - pip
  - opencv==4.5.2
  - pip:
      - transforms3d
      - pydegensac
      - h5py
      - tqdm
      - pyyaml
      - psutil
      - einops
      - kornia
      - yacs
      - gdown
      - pillow