name: immatch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - python=3.7
  - pytorch
  - torchvision
  - jupyter
  - scipy
  - matplotlib
  - pip
  - opencv==4.5.2
  - pip:
      - transforms3d
      - pydegensac
      - h5py
      - tqdm
      - pyyaml
      - psutil
  - pillow=6.0.0=py37he7afcd5_0 # To reproduce patch2pix cvpr21 results only