default: &default
    class: 'Patch2PixRefined'
    ckpt: 'pretrained/patch2pix/patch2pix_pretrained.pth'
    imsize: 1024
coarse_default: &coarse_default
    name: 'SuperGlue'
    weights: 'outdoor'    
    sinkhorn_iterations: 50
    max_keypoints: 4096
    nms_radius: 4
    imsize: 1024
inloc:
    <<: *default
    match_threshold: 0.1
    imsize: 1600 
    pairs: 'pairs-query-netvlad40-temporal.txt' 
    rthres: 48
    skip_matches: 20 
    coarse:
        <<: *coarse_default
        match_threshold: 0.1
        imsize: 1600
